name: 'cicd-build-push-on-gcp-action'
description: 'Action to build and push on GCR the artifact'
author: 'lelered'

inputs:
  release-version:
    description: "Release version"
    required: true
  service-account-email:
    description: 'Service account email for Google auth login.'
    required: true
  workload-identity-provider:
    description: 'Workload identity provider Google auth login.'
    required: true
  gcr-domain:
    description: 'Registry Domain (for example: "europe-west4-docker.pkg.dev").'
    required: true
  gcr-path:
    description: ''
    required: true
  build-args:
    description: ''
    required: false
  additional-targets:
    description: 'JSON array of additional build targets with postfix (e.g. ["migrations", "worker"])'
    required: false
    default: '[]'


outputs:
  image-gcr-url:
    description: ""
    value: "https://${{ inputs.gcr-domain }}/${{ inputs.gcr-path }}"

runs:
  using: "composite"
  steps:
    -
      name: Checkout
      uses: actions/checkout@v6
      with:
        submodules: true
        # token: ${{ secrets.BUNDLE_GITHUB_COM }}
    -
      # Autenticazione con Workload Identity Federation
      name: Setup Google auth
      id: auth
      uses: google-github-actions/auth@v3
      with:
        workload_identity_provider: ${{ inputs.workload-identity-provider }}
        service_account: ${{ inputs.service-account-email }}
        token_format: 'access_token'
    -
      name: Setup docker
      uses: docker/setup-buildx-action@v3
    -
      name: Authenticate docker
      shell: bash
      run: |
        gcloud auth configure-docker --quiet ${{ inputs.gcr-domain }}
    -
      name: Build and push
      uses: docker/build-push-action@v6
      with:
        build-args: ${{ inputs.build-args }}
        context: .
        push: true
        tags: |
          ${{ inputs.gcr-domain }}/${{ inputs.gcr-path }}:${{github.sha}}
          ${{ inputs.gcr-domain }}/${{ inputs.gcr-path }}:${{inputs.release-version}}
        cache-from: type=gha
        cache-to: type=gha,mode=max
    -
      name: Build and push additional targets
      if: inputs.additional-targets != '[]'
      shell: bash
      run: |
        targets='${{ inputs.additional-targets }}'
        echo "Processing targets: $targets"
        
        # Itera su ogni target nell'array JSON
        for target in $(echo "$targets" | jq -r '.[]'); do
          echo "Building target: $target"
          
          docker buildx build \
            ${{ inputs.build-args && format('--build-arg {0}', inputs.build-args) || '' }} \
            --target "$target" \
            --tag "${{ inputs.gcr-domain }}/${{ inputs.gcr-path }}:${{ inputs.release-version }}-$target" \
            --push \
            --cache-from type=gha \
            --cache-to type=gha,mode=max \
            .
        done
